config/routes.rb
Rails.application.routes.draw do
  resources :songs
  resources :artists
  root 'rock#roll'
  get 'artists.id' =>'artists#id'

end

app/models/artist.rb
class Artist < ActiveRecord::Base

	has_many :songs
	validates :name, presence: true, uniqueness: true
end

app/models/song.rb
class Song < ActiveRecord::Base

	belongs_to :artist
	validates :name, presence: true
  validates :artist_id, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
    @songs = Song.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy

    @artist.destroy
    @artist.songs.each do |song|
      song.destroy
    end
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist and artist songs were successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name)
    end
end

app/controllers/rock_controller.rb
class RockController < ApplicationController
  def roll

  	@songs = Song.order('rating DESC').limit(5)
  	@artist = Artist.all

  end
  



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    # @song = Song.find(params[:id])
    # @artist = Artist.find(params[:artist_id])
  end

  # GET /songs/new
  def new
    @song = Song.new
    @artists = Artist.all

  end

  # GET /songs/1/edit
  def edit
    @artists = Artist.all
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)
    @artists = Artist.all

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    @artists = Artist.all

    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :rating, :artist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/rock_helper.rb
module RockHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= "#{artist.songs.name}" %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTop5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,900italic' rel='stylesheet' type='text/css'>
</head>
<body>
<div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h2 class="masthead-brand" style="font-family: 'Poiret One', cursive;"><%= image_tag "music_icon3.png" %>Heather's Favorite Grooves</h1>


              <nav>
                <ul class="nav masthead-nav">
                  <li><%= link_to "Top 5", root_path %></li>
                  <li><%= link_to "Artist", artists_path %></li>
                  <li><%= link_to "Songs", songs_path %> </li>
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            <%= yield %>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Groove To The Beat Of My Music &copy; 2016</p>
            </div>
          </div>

        </div>

      </div>

    </div>









</body>
</html>

app/views/rock/roll.html.erb
<h1 style="font-family: 'Poiret One', cursive;"><strong>Here are my TOP 5 Grooves<srong></h1>


<table class ="table" >
  <thead>
    <tr>
      <th>Song Name</th>
	    <th>Rating</th>
	    <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.rating %></td>
        <td><%= song.artist.name %><td>
        <td><%= link_to 'Artist Page', artist_path(song.artist.id) %></td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "well" >

  <div class="field" style="color:black;">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field" style="color:black;">
  
    <%= f.select :rating, %w(1 2 3 4 5 6 7 8 9 10), {include_blank:  'Rating'} %>
  </div>
  <div class="field" style="color:black;">
   
    <%= f.select(:artist_id, @artists.collect {|a| [ a.name, a.id ] }, {:include_blank => 'Please select an artist'}) %>
  </div>
  <div class="actions" style="color:black;">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Music Line-up</h1>

<p><%= link_to 'Add a Song', new_song_path, class: "glyphicon glyphicon-plus", style: "color: white;" %></p>


  

  <div class ="row">
    <% @songs.each do |song| %>
      <div class="col-md-6">
        <div class ="well" style="height:250px; width:300px;">
        <p style="font-size: 20px; font-family: 'Playfair Display', serif;"><em><strong><%= "#{song.name}" %></em></strong></p>
        <p> <%= "#{song.rating} " %>our of 10</p>
        <p>
           <% "#{song.rating}".to_i.times do %>
          <span class="glyphicon glyphicon-star"></span>
          <% end %>
        </p>



        <p>By:<strong><%= "#{song.artist.name}" %></strong></p>
        <p>-------------------------------------------</p>
        

        <p><%= link_to '',  edit_song_path(song), class: "glyphicon glyphicon-pencil", style: "color: white;" %>
        <%= link_to '', song, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash", style: "color: white;" %></p>
      </div>
    </div>
    <% end %>
  </div>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @song.rating %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist.name %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>